### ISSUE TITLE
HDMI

### ISSUE THREAD

**Issue by hsulei** [chuxubank/MSI-GP62-Hackintosh#1]
my computer is same , i use your config ,but HDMI is not work , how to fix it ?

**Comment by chuxubank** [comment]
I don't have any external monitor, so no work on the HDMI (not even test).
Maybe this guid can help. [[GUIDE] General Framebuffer Patching Guide (HDMI Black Screen Problem)](https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/)

**Comment by hsulei** [comment]
应该是config.plist中有些配置有问题，我从网上重新找了一个配置文件，能够支持双屏

**Comment by chuxubank** [comment]
OK，如果你测试成功也欢迎提PR

**Comment by chuxubank** [comment]
@hsulei 老哥能不能提供一下你的配置文件? 我现在也在测试...

**Comment by hsulei** [comment]
@chuxubank 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Comment</key>
		<string>This file is for Skylake graphics that are natively supported</string>
		<key>ACPI</key>
		<dict>
			<key>AutoMerge</key>
			<true/>
			<key>FixHeaders</key>
			<true/>
			<key>Comment-DisabledAML</key>
			<string>Disable other forms of CPU PM due to SSDT/Generate/PluginType=true</string>
			<key>DisabledAML</key>
			<array>
				<string>SSDT.aml</string>
				<string>SSDT-XCPM.aml</string>
				<string>SSDT-PluginType1.aml</string>
			</array>
			<key>DSDT</key>
			<dict>
				<key>DropOEM_DSM</key>
				<false/>
				<key>Fixes</key>
				<dict>
					<key>Comment-IRQ Fix</key>
					<string>The following fixes may be needed for onboard audio/USB/etc</string>
					<key>FixTMR</key>
					<false/>
					<key>FixRTC</key>
					<false/>
					<key>FixIPIC</key>
					<false/>
					<key>FixHPET</key>
					<false/>
				</dict>
				<key>Patches</key>
				<array>
					<dict>
						<key>Comment</key>
						<string>change OSID to XSID (to avoid match against _OSI XOSI patch)</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>T1NJRA==</data>
						<key>Replace</key>
						<data>WFNJRA==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change _OSI to XOSI</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>X09TSQ==</data>
						<key>Replace</key>
						<data>WE9TSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change _DSM to XDSM</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>X0RTTQ==</data>
						<key>Replace</key>
						<data>WERTTQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change EC0 to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>RUMwXw==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change H_EC to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>SF9FQw==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change ECDV to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>RUNEVg==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change HDAS to HDEF</string>
						<key>Find</key>
						<data>SERBUw==</data>
						<key>Replace</key>
						<data>SERFRg==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change HECI to IMEI</string>
						<key>Find</key>
						<data>SEVDSQ==</data>
						<key>Replace</key>
						<data>SU1FSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change MEI to IMEI</string>
						<key>Find</key>
						<data>TUVJXw==</data>
						<key>Replace</key>
						<data>SU1FSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change GFX0 to IGPU</string>
						<key>Find</key>
						<data>R0ZYMA==</data>
						<key>Replace</key>
						<data>SUdQVQ==</data>
					</dict>
				</array>
			</dict>
			<key>DropTables</key>
			<array>
				<dict>
					<key>Signature</key>
					<string>#MCFG</string>
				</dict>
				<dict>
					<key>Signature</key>
					<string>DMAR</string>
				</dict>
				<dict>
					<key>Signature</key>
					<string>SSDT</string>
					<key>TableId</key>
					<string>xh_rvp10</string>
				</dict>
			</array>
			<key>SSDT</key>
			<dict>
				<key>DropOem</key>
				<false/>
				<key>Generate</key>
				<dict>
					<key>PluginType</key>
					<true/>
				</dict>
				<key>NoOemTableId</key>
				<false/>
			</dict>
		</dict>
		<key>Boot</key>
		<dict>
			<key>Arguments</key>
			<string>dart=0 nv_disable=1 -cdfon -igfxnohdmi</string>
			<key>DefaultVolume</key>
			<string>LastBootedVolume</string>
			<key>NeverHibernate</key>
			<true/>
			<key>Secure</key>
			<false/>
			<key>Timeout</key>
			<integer>5</integer>
		</dict>
		<key>Devices</key>
		<dict>
			<key>AddProperties</key>
			<array>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>name</string>
					<key>Value</key>
					<data>I2Rpc3BsYXkA</data>
					<key>Comment</key>
					<string>Inject &quot;name&quot; as (data)&quot;#display&quot; to disable graphics drivers on NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>IOName</string>
					<key>Value</key>
					<string>#display</string>
					<key>Comment</key>
					<string>Inject &quot;IOName&quot; as &quot;#display&quot; to disable graphics drivers on NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>class-code</string>
					<key>Value</key>
					<data>/////w==</data>
					<key>Comment</key>
					<string>Inject bogus class-code to prevent graphics drivers loading for NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>name</string>
					<key>Value</key>
					<data>I2Rpc3BsYXkA</data>
					<key>Comment</key>
					<string>Inject &quot;name&quot; as (data)&quot;#display&quot; to disable graphics drivers on AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>IOName</string>
					<key>Value</key>
					<string>#display</string>
					<key>Comment</key>
					<string>Inject &quot;IOName&quot; as &quot;#display&quot; to disable graphics drivers on AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>class-code</string>
					<key>Value</key>
					<data>/////w==</data>
					<key>Comment</key>
					<string>Inject bogus class-code to prevent graphics drivers loading for AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>vendor-id</string>
					<key>Value</key>
					<data>//8AAA==</data>
					<key>Comment</key>
					<string>Inject bogus vendor-id to prevent graphics drivers loading for AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>device-id</string>
					<key>Value</key>
					<data>//8AAA==</data>
					<key>Comment</key>
					<string>Inject bogus device-id to prevent graphics drivers loading for AMD</string>
				</dict>
			</array>
			<key>Audio</key>
			<dict>
				<key>Inject</key>
				<integer>7</integer>
			</dict>
			<key>Properties</key>
			<dict>
				<key>PciRoot(0)/Pci(0x02,0)</key>
				<dict>
					<key>AAPL,ig-platform-id</key>
					<data>AAAbGQ==</data>
					<key>#hda-gfx</key>
					<string>onboard-1</string>
					<key>#AAPL00,override-no-connect</key>
					<data></data>
					<key>#AAPL00,override-no-edid</key>
					<data></data>
					<key># DVMT-prealloc</key>
					<string>32MB BIOS, 19MB framebuffer, 9MB cursor bytes (credit RehabMan)</string>
					<key>framebuffer-patch-enable</key>
					<integer>1</integer>
					<key>framebuffer-stolenmem</key>
					<data>AAAwAQ==</data>
					<key>framebuffer-fbmem</key>
					<data>AACQAA==</data>
					<key>## @0 LVDS-&gt;DP</key>
					<string></string>
					<key>#framebuffer-con0-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con0-type</key>
					<data>AAQAAA==</data>
					<key>## @1 HDMI</key>
					<string></string>
					<key>#framebuffer-con1-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con1-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con1-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con1-pipe</key>
					<data>EgAAAA==</data>
					<key>## @2 HDMI</key>
					<string></string>
					<key>#framebuffer-con2-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con2-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con2-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con2-pipe</key>
					<data>EgAAAA==</data>
					<key>## @3 HDMI</key>
					<string></string>
					<key>#framebuffer-con3-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con3-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con3-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con3-pipe</key>
					<data>EgAAAA==</data>
					<key>## patch0</key>
					<string>Enable lid wake for 0x19260002 credit syscl/lighting/Yating Zhou</string>
					<key>#framebuffer-patch0-enable</key>
					<integer>1</integer>
					<key>#framebuffer-patch0-find</key>
					<data>ChMDAAAABgAAAAAAAAAAAA==</data>
					<key>#framebuffer-patch0-replace</key>
					<data>DxMDAAAABgAAAAAAAAAAAA==</data>
					<key>## patch1</key>
					<string>Enable lid wake for 0x19260004 credit syscl/lighting/Yating Zhou</string>
					<key>#framebuffer-patch1-enable</key>
					<integer>1</integer>
					<key>#framebuffer-patch1-find</key>
					<data>CgsDAAAHBgADAAAABAAAAA==</data>
					<key>#framebuffer-patch1-replace</key>
					<data>DwsDAAAHBgADAAAABAAAAA==</data>
				</dict>
				<key>PciRoot(0)/Pci(0x1f,3)</key>
				<dict>
					<key>layout-id</key>
					<integer>99</integer>
					<key>#PinConfigurations</key>
					<data></data>
					<key>#hda-gfx</key>
					<string>onboard-1</string>
					<key>#no-controller-patch</key>
					<integer>1</integer>
				</dict>
			</dict>
			<key>USB</key>
			<dict>
				<key>FixOwnership</key>
				<true/>
				<key>AddClockID</key>
				<true/>
				<key>Inject</key>
				<true/>
			</dict>
			<key>UseIntelHDMI</key>
			<false/>
		</dict>
		<key>DisableDrivers</key>
		<array>
			<string>VBoxHfs</string>
		</array>
		<key>GUI</key>
		<dict>
			<key>Custom</key>
			<dict>
				<key>Entries</key>
				<array>
					<dict>
						<key>Hidden</key>
						<false/>
						<key>Type</key>
						<string>OSXRecovery</string>
					</dict>
					<dict>
						<key>Type</key>
						<string>Windows</string>
						<key>Title</key>
						<string>Windows</string>
					</dict>
				</array>
			</dict>
			<key>Hide</key>
			<array>
				<string>Preboot</string>
			</array>
			<key>Mouse</key>
			<dict>
				<key>Enabled</key>
				<false/>
			</dict>
			<key>Scan</key>
			<dict>
				<key>Entries</key>
				<true/>
				<key>Legacy</key>
				<false/>
				<key>Linux</key>
				<true/>
				<key>Tool</key>
				<true/>
			</dict>
			<key>#ScreenResolution</key>
			<string>1920x1080</string>
			<key>Theme</key>
			<string>BGM</string>
		</dict>
		<key>Graphics</key>
		<dict>
			<key>#EDID</key>
			<dict>
				<key>Inject</key>
				<false/>
			</dict>
			<key>#ig-platform-id</key>
			<string>0x191b0000</string>
			<key>Inject</key>
			<dict>
				<key>ATI</key>
				<true/>
				<key>Intel</key>
				<false/>
				<key>NVidia</key>
				<true/>
			</dict>
		</dict>
		<key>KernelAndKextPatches</key>
		<dict>
			<key>AppleRTC</key>
			<true/>
			<key>DellSMBIOSPatch</key>
			<false/>
			<key>KernelLapic</key>
			<true/>
			<key>KernelPm</key>
			<true/>
			<key>ForceKextsToLoad</key>
			<array>
				<string>\System\Library\Extensions\IONetworkingFamily.kext</string>
			</array>
			<key>KextsToPatch</key>
			<array/>
			<key>KernelToPatch</key>
			<array>
				<dict>
					<key>Comment</key>
					<string>MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>ILniAAAADzA=</data>
					<key>Replace</key>
					<data>ILniAAAAkJA=</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Disable panic kext logging on 10.13 release kernel (credit vit9696)</string>
					<key>MatchOS</key>
					<string>10.13.x</string>
					<key>Find</key>
					<data>igKEwHRE</data>
					<key>Replace</key>
					<data>igKEwOtE</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Disable panic kext logging on 10.14 release kernel (credit vit9696)</string>
					<key>MatchOS</key>
					<string>10.14.x</string>
					<key>Find</key>
					<data>igKEwHRC</data>
					<key>Replace</key>
					<data>igKEwOtC</data>
				</dict>
			</array>
		</dict>
		<key>RtVariables</key>
		<dict>
			<key>CsrActiveConfig</key>
			<string>0x67</string>
			<key>BooterConfig</key>
			<string>0x28</string>
		</dict>
		<key>SMBIOS</key>
		<dict>
			<key>ProductName</key>
			<string>MacBookPro13,1</string>
			<key>Trust</key>
			<true/>
		</dict>
		<key>SystemParameters</key>
		<dict>
			<key>InjectKexts</key>
			<string>Detect</string>
		</dict>
	</dict>
</plist>

**Comment by hsulei** [comment]
@chuxubank 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Comment</key>
		<string>This file is for Skylake graphics that are natively supported</string>
		<key>ACPI</key>
		<dict>
			<key>AutoMerge</key>
			<true/>
			<key>FixHeaders</key>
			<true/>
			<key>Comment-DisabledAML</key>
			<string>Disable other forms of CPU PM due to SSDT/Generate/PluginType=true</string>
			<key>DisabledAML</key>
			<array>
				<string>SSDT.aml</string>
				<string>SSDT-XCPM.aml</string>
				<string>SSDT-PluginType1.aml</string>
			</array>
			<key>DSDT</key>
			<dict>
				<key>DropOEM_DSM</key>
				<false/>
				<key>Fixes</key>
				<dict>
					<key>Comment-IRQ Fix</key>
					<string>The following fixes may be needed for onboard audio/USB/etc</string>
					<key>FixTMR</key>
					<false/>
					<key>FixRTC</key>
					<false/>
					<key>FixIPIC</key>
					<false/>
					<key>FixHPET</key>
					<false/>
				</dict>
				<key>Patches</key>
				<array>
					<dict>
						<key>Comment</key>
						<string>change OSID to XSID (to avoid match against _OSI XOSI patch)</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>T1NJRA==</data>
						<key>Replace</key>
						<data>WFNJRA==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change _OSI to XOSI</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>X09TSQ==</data>
						<key>Replace</key>
						<data>WE9TSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change _DSM to XDSM</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>X0RTTQ==</data>
						<key>Replace</key>
						<data>WERTTQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change EC0 to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>RUMwXw==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change H_EC to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>SF9FQw==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change ECDV to EC</string>
						<key>Disabled</key>
						<true/>
						<key>Find</key>
						<data>RUNEVg==</data>
						<key>Replace</key>
						<data>RUNfXw==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change HDAS to HDEF</string>
						<key>Find</key>
						<data>SERBUw==</data>
						<key>Replace</key>
						<data>SERFRg==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change HECI to IMEI</string>
						<key>Find</key>
						<data>SEVDSQ==</data>
						<key>Replace</key>
						<data>SU1FSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change MEI to IMEI</string>
						<key>Find</key>
						<data>TUVJXw==</data>
						<key>Replace</key>
						<data>SU1FSQ==</data>
					</dict>
					<dict>
						<key>Comment</key>
						<string>change GFX0 to IGPU</string>
						<key>Find</key>
						<data>R0ZYMA==</data>
						<key>Replace</key>
						<data>SUdQVQ==</data>
					</dict>
				</array>
			</dict>
			<key>DropTables</key>
			<array>
				<dict>
					<key>Signature</key>
					<string>#MCFG</string>
				</dict>
				<dict>
					<key>Signature</key>
					<string>DMAR</string>
				</dict>
				<dict>
					<key>Signature</key>
					<string>SSDT</string>
					<key>TableId</key>
					<string>xh_rvp10</string>
				</dict>
			</array>
			<key>SSDT</key>
			<dict>
				<key>DropOem</key>
				<false/>
				<key>Generate</key>
				<dict>
					<key>PluginType</key>
					<true/>
				</dict>
				<key>NoOemTableId</key>
				<false/>
			</dict>
		</dict>
		<key>Boot</key>
		<dict>
			<key>Arguments</key>
			<string>dart=0 nv_disable=1 -cdfon -igfxnohdmi</string>
			<key>DefaultVolume</key>
			<string>LastBootedVolume</string>
			<key>NeverHibernate</key>
			<true/>
			<key>Secure</key>
			<false/>
			<key>Timeout</key>
			<integer>5</integer>
		</dict>
		<key>Devices</key>
		<dict>
			<key>AddProperties</key>
			<array>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>name</string>
					<key>Value</key>
					<data>I2Rpc3BsYXkA</data>
					<key>Comment</key>
					<string>Inject &quot;name&quot; as (data)&quot;#display&quot; to disable graphics drivers on NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>IOName</string>
					<key>Value</key>
					<string>#display</string>
					<key>Comment</key>
					<string>Inject &quot;IOName&quot; as &quot;#display&quot; to disable graphics drivers on NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>NVidia</string>
					<key>Key</key>
					<string>class-code</string>
					<key>Value</key>
					<data>/////w==</data>
					<key>Comment</key>
					<string>Inject bogus class-code to prevent graphics drivers loading for NVidia</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>name</string>
					<key>Value</key>
					<data>I2Rpc3BsYXkA</data>
					<key>Comment</key>
					<string>Inject &quot;name&quot; as (data)&quot;#display&quot; to disable graphics drivers on AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>IOName</string>
					<key>Value</key>
					<string>#display</string>
					<key>Comment</key>
					<string>Inject &quot;IOName&quot; as &quot;#display&quot; to disable graphics drivers on AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>class-code</string>
					<key>Value</key>
					<data>/////w==</data>
					<key>Comment</key>
					<string>Inject bogus class-code to prevent graphics drivers loading for AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>vendor-id</string>
					<key>Value</key>
					<data>//8AAA==</data>
					<key>Comment</key>
					<string>Inject bogus vendor-id to prevent graphics drivers loading for AMD</string>
				</dict>
				<dict>
					<key>Device</key>
					<string>ATI</string>
					<key>Key</key>
					<string>device-id</string>
					<key>Value</key>
					<data>//8AAA==</data>
					<key>Comment</key>
					<string>Inject bogus device-id to prevent graphics drivers loading for AMD</string>
				</dict>
			</array>
			<key>Audio</key>
			<dict>
				<key>Inject</key>
				<integer>7</integer>
			</dict>
			<key>Properties</key>
			<dict>
				<key>PciRoot(0)/Pci(0x02,0)</key>
				<dict>
					<key>AAPL,ig-platform-id</key>
					<data>AAAbGQ==</data>
					<key>#hda-gfx</key>
					<string>onboard-1</string>
					<key>#AAPL00,override-no-connect</key>
					<data></data>
					<key>#AAPL00,override-no-edid</key>
					<data></data>
					<key># DVMT-prealloc</key>
					<string>32MB BIOS, 19MB framebuffer, 9MB cursor bytes (credit RehabMan)</string>
					<key>framebuffer-patch-enable</key>
					<integer>1</integer>
					<key>framebuffer-stolenmem</key>
					<data>AAAwAQ==</data>
					<key>framebuffer-fbmem</key>
					<data>AACQAA==</data>
					<key>## @0 LVDS-&gt;DP</key>
					<string></string>
					<key>#framebuffer-con0-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con0-type</key>
					<data>AAQAAA==</data>
					<key>## @1 HDMI</key>
					<string></string>
					<key>#framebuffer-con1-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con1-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con1-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con1-pipe</key>
					<data>EgAAAA==</data>
					<key>## @2 HDMI</key>
					<string></string>
					<key>#framebuffer-con2-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con2-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con2-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con2-pipe</key>
					<data>EgAAAA==</data>
					<key>## @3 HDMI</key>
					<string></string>
					<key>#framebuffer-con3-enable</key>
					<integer>1</integer>
					<key>#framebuffer-con3-type</key>
					<data>AAgAAA==</data>
					<key>#framebuffer-con3-flags</key>
					<data>hwEAAA==</data>
					<key>#framebuffer-con3-pipe</key>
					<data>EgAAAA==</data>
					<key>## patch0</key>
					<string>Enable lid wake for 0x19260002 credit syscl/lighting/Yating Zhou</string>
					<key>#framebuffer-patch0-enable</key>
					<integer>1</integer>
					<key>#framebuffer-patch0-find</key>
					<data>ChMDAAAABgAAAAAAAAAAAA==</data>
					<key>#framebuffer-patch0-replace</key>
					<data>DxMDAAAABgAAAAAAAAAAAA==</data>
					<key>## patch1</key>
					<string>Enable lid wake for 0x19260004 credit syscl/lighting/Yating Zhou</string>
					<key>#framebuffer-patch1-enable</key>
					<integer>1</integer>
					<key>#framebuffer-patch1-find</key>
					<data>CgsDAAAHBgADAAAABAAAAA==</data>
					<key>#framebuffer-patch1-replace</key>
					<data>DwsDAAAHBgADAAAABAAAAA==</data>
				</dict>
				<key>PciRoot(0)/Pci(0x1f,3)</key>
				<dict>
					<key>layout-id</key>
					<integer>99</integer>
					<key>#PinConfigurations</key>
					<data></data>
					<key>#hda-gfx</key>
					<string>onboard-1</string>
					<key>#no-controller-patch</key>
					<integer>1</integer>
				</dict>
			</dict>
			<key>USB</key>
			<dict>
				<key>FixOwnership</key>
				<true/>
				<key>AddClockID</key>
				<true/>
				<key>Inject</key>
				<true/>
			</dict>
			<key>UseIntelHDMI</key>
			<false/>
		</dict>
		<key>DisableDrivers</key>
		<array>
			<string>VBoxHfs</string>
		</array>
		<key>GUI</key>
		<dict>
			<key>Custom</key>
			<dict>
				<key>Entries</key>
				<array>
					<dict>
						<key>Hidden</key>
						<false/>
						<key>Type</key>
						<string>OSXRecovery</string>
					</dict>
					<dict>
						<key>Type</key>
						<string>Windows</string>
						<key>Title</key>
						<string>Windows</string>
					</dict>
				</array>
			</dict>
			<key>Hide</key>
			<array>
				<string>Preboot</string>
			</array>
			<key>Mouse</key>
			<dict>
				<key>Enabled</key>
				<false/>
			</dict>
			<key>Scan</key>
			<dict>
				<key>Entries</key>
				<true/>
				<key>Legacy</key>
				<false/>
				<key>Linux</key>
				<true/>
				<key>Tool</key>
				<true/>
			</dict>
			<key>#ScreenResolution</key>
			<string>1920x1080</string>
			<key>Theme</key>
			<string>BGM</string>
		</dict>
		<key>Graphics</key>
		<dict>
			<key>#EDID</key>
			<dict>
				<key>Inject</key>
				<false/>
			</dict>
			<key>#ig-platform-id</key>
			<string>0x191b0000</string>
			<key>Inject</key>
			<dict>
				<key>ATI</key>
				<true/>
				<key>Intel</key>
				<false/>
				<key>NVidia</key>
				<true/>
			</dict>
		</dict>
		<key>KernelAndKextPatches</key>
		<dict>
			<key>AppleRTC</key>
			<true/>
			<key>DellSMBIOSPatch</key>
			<false/>
			<key>KernelLapic</key>
			<true/>
			<key>KernelPm</key>
			<true/>
			<key>ForceKextsToLoad</key>
			<array>
				<string>\System\Library\Extensions\IONetworkingFamily.kext</string>
			</array>
			<key>KextsToPatch</key>
			<array/>
			<key>KernelToPatch</key>
			<array>
				<dict>
					<key>Comment</key>
					<string>MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>ILniAAAADzA=</data>
					<key>Replace</key>
					<data>ILniAAAAkJA=</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Disable panic kext logging on 10.13 release kernel (credit vit9696)</string>
					<key>MatchOS</key>
					<string>10.13.x</string>
					<key>Find</key>
					<data>igKEwHRE</data>
					<key>Replace</key>
					<data>igKEwOtE</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Disable panic kext logging on 10.14 release kernel (credit vit9696)</string>
					<key>MatchOS</key>
					<string>10.14.x</string>
					<key>Find</key>
					<data>igKEwHRC</data>
					<key>Replace</key>
					<data>igKEwOtC</data>
				</dict>
			</array>
		</dict>
		<key>RtVariables</key>
		<dict>
			<key>CsrActiveConfig</key>
			<string>0x67</string>
			<key>BooterConfig</key>
			<string>0x28</string>
		</dict>
		<key>SMBIOS</key>
		<dict>
			<key>ProductName</key>
			<string>MacBookPro13,1</string>
			<key>Trust</key>
			<true/>
		</dict>
		<key>SystemParameters</key>
		<dict>
			<key>InjectKexts</key>
			<string>Detect</string>
		</dict>
	</dict>
</plist>

```

**Comment by hsulei** [comment]
@chuxubank  我是使用这个配置成功，但还是有问题，dp能使用但是如果在使用过程中拔掉的话会黑屏，推荐还是使用hdmi ， 另外，如果双屏没有问题，但是没有声音的话，还是要修改一个`Audio`的注入值

**Comment by chuxubank** [comment]
@hsulei 666 一下就点亮了 厉害
我再看看哪里有改动了手动merge一下

**Comment by hsulei** [comment]
我用到现在，除了那个dp的线，其他的基本没啥问题，wifi反正无解，耳机也能用，亮度也能调节，剩下的就还有就是键盘的键位有问题

**Comment by hsulei** [comment]
反正10.15我是不敢升了，之前10.13升10.14折腾了好几天，好不容易找到这个还算完美的配置文件

**Comment by chuxubank** [comment]
我大致看了下好像就是 Rehabman 的那个 [config_HD515_520_530_540.plist](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD515_520_530_540.plist) 稍微改了改, 但这就很奇怪了, 我今天明明试过这个文件, 但却没成功...

**Comment by hsulei** [comment]
是的，主要就是这个文件，我印象中我就改了一下Audio的注入参数，，这个 config_HD515_520_530_540.plist文件我也找了好多，但就这一个有用的

**Comment by chuxubank** [comment]
找到原因了 只需要吧 `SMBIOS->ProductName` 改成 `MacBookPro13,1` 即可... 网上大部分人都和我一样用的 `MacBookPro13,3` (HD530的推荐设置)...

**Comment by hsulei** [comment]
过一阵子试试10.15

**Comment by chuxubank** [comment]
OK, 我最终采用 https://github.com/PLChinDev/Dell-Precision-5510-Catalina 的方法, 好像只有这样才能输出4k(30hz). 而 `MacBookPro13,1` 默认是1080p(60hz).
