### ISSUE TITLE
dual monitor

### ISSUE THREAD

**Issue by SwaggyZhang** [chuxubank/MSI-GP62-Hackintosh#11]
大佬你好，我的电脑使用的也是i7-6700HQ，系统是10.15.7，引导为opencore 0.8.0，SMBIOS MacBookPro13,3
目前网卡，蓝牙以及声卡均已驱动，但HDMI不正常，具体表现为：
不外接显示器开机，笔记本内建显示正常，但此时插外接显示器没反应，不识别
开机时外接显示器，笔记本和显示器会同步显示内容直到logo读条，之后笔记本黑屏(点亮状态)，只有外接显示器可用，请问您出现过此类情况吗？
（已按dortania的文档添加过framebuffer但没用）

**Comment by chuxubank** [comment]
@SwaggyZhang https://github.com/chuxubank/MSI-GP62-Hackintosh#hdmidp 我README文档中的方法试过吗
即你的启动项中有没有 `agdpmod=vit9696` 这个？
不过我最近不使用黑苹果了，可能没法帮你验证 OC 0.8.0，但我觉得应该可以通用。

**Comment by SwaggyZhang** [comment]
> @SwaggyZhang https://github.com/chuxubank/MSI-GP62-Hackintosh#hdmidp 我README文档中的方法试过吗 即你的启动项中有没有 `agdpmod=vit9696` 这个？ 不过我最近不使用黑苹果了，可能没法帮你验证 OC 0.8.0，但我觉得应该可以通用。

哦哦我启动项里没有加agdpmod=vit9696，但是我发现一个奇怪的现象，笔记本内建显示器是可以识别的，但是不能立即使用，需要睡眠长时间之后再唤醒，这时就可以双屏了，我实在是不懂这个原理。。。

**Comment by chuxubank** [comment]
是的 你说的这个现象我也遇到过 #4 里应该也说过，可以用 hotcorner 触发息屏，再次点亮就两个屏幕都亮了。

https://github.com/chuxubank/MSI-GP62-Hackintosh/issues/4#issuecomment-953953136 里提到了解决方案 应该是换用 0x19260002 的 platformid 你可以试一下

**Comment by SwaggyZhang** [comment]
嗯嗯好德，我有时间试一下，我的电脑是联想小新700-15isk，因为Catalina出这个问题我又装了一次Mojave，结果还是这个奇怪的问题，谢谢大佬~试完之后我来报告！

by the way，如果我现在用官方的App Store升级大版本，自己装的homebrew那些还会在吗？

**Comment by chuxubank** [comment]
在的 但是可能会要安装新的 Xcode 命令行插件后才能用

**Comment by SwaggyZhang** [comment]
明白了，谢谢大佬！待我回去试一下那个解决方案！然后收拾收拾准备Catalina

**Comment by SwaggyZhang** [comment]
> 是的 你说的这个现象我也遇到过 #4 里应该也说过，可以用 hotcorner 触发息屏，再次点亮就两个屏幕都亮了。
> 
> [#4 (comment)](https://github.com/chuxubank/MSI-GP62-Hackintosh/issues/4#issuecomment-953953136) 里提到了解决方案 应该是换用 0x19260002 的 platformid 你可以试一下

我回去试了一下，发现hackintool在`0x19260002`时SMBIOS显示的是iMac设备，就没敢动，然后`agdpmod`加上去后还是会出现先睡眠再唤醒才能激活双屏的现象，能凑合用的话就先不管了，今天一早更了Catalina，也没有数据丢失，终于可以愉快使用airpods pro了。
谢谢大佬！

**Comment by chuxubank** [comment]
嗯 如果不换 platformid 应该是没法解决的，我个人觉得可以尝试一下，SMBIOS 保持原来的就好，不要用 Hackintool，直接手动改 config.plist。
另外如果原本就可以识别到外接显示器，则 `agdpmod` 启动项也可以不用了，这个是识别不到外接显示器才加的。

**Comment by SwaggyZhang** [comment]
谢谢大佬！我查了whatevergreen的文档，agdpmod是取消检查board-id的，如果改了platform-id而且不加agdpmod我感觉可能会报错，所以对应的smbios可能也要改。
我没敢试，能凑合用我就不太敢再折腾了，最近时间比较少哈哈



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月17日 08:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [chuxubank/MSI-GP62-Hackintosh] dual monitor (Issue #11) |

嗯 如果不换 platformid 应该是没法解决的，我个人觉得可以尝试一下，SMBIOS 保持原来的就好，不要用 Hackintool，直接手动改 config.plist。
另外如果原本就可以识别到外接显示器，则 agdpmod 启动项也可以不用了，这个是识别不到外接显示器才加的。
