### ISSUE TITLE
大佬我和你一样的型号，但是装的时候会卡在这儿

### ISSUE THREAD

**Issue by KonpakuSyl** [chuxubank/MSI-GP62-Hackintosh#2]
![IMG_5301](https://user-images.githubusercontent.com/33344292/59549142-e5caa580-8f8b-11e9-9b22-7d1e2dc6870b.JPG)

**Comment by chuxubank** [comment]
安装和日常启动的EFI可能有略微不同，请按照 [[Guide] Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) 中的步骤进行安装。
确保安装盘已格式化为APFS格式并移除不必要的kext。

**Comment by KonpakuSyl** [comment]
> 安装和日常启动的EFI可能有略微不同，请按照 [[Guide] Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) 中的步骤进行安装。
> 确保安装盘已格式化为APFS格式并移除不必要的kext。

大佬，我按照教程安装，但是出现了这个问题
![20190616213943](https://user-images.githubusercontent.com/33344292/59564946-7df58700-907f-11e9-984c-90b61450d044.jpg)

**Comment by chuxubank** [comment]
可能是BIOS版本不同导致的问题，我使用的是 [E16J5IMS.11D](https://cn.msi.com/Laptop/support/GP62-6QG-1071XCN) 版本。
也可以尝试移除 `CLOVER/ACPI/patched/` 目录下的 `SSDT-FAN.aml` 后再尝试。

**Comment by aiisalive** [comment]
![f1e6db7257e42a0f8e3c22c9e5dc7a4](https://user-images.githubusercontent.com/35070819/64304324-09672000-cfbe-11e9-92c8-617077ade0de.jpg)
,你好，我的是只有win和Ubuntu两个启动项，没有安装的启动项

**Comment by aiisalive** [comment]
删除了<string>Preboot</string>还是这样的，麻烦大佬帮我看看这是什么问题吧

**Comment by aiisalive** [comment]
> > 安装和日常启动的EFI可能有略微不同，请按照[[指南]使​​用Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/)中的步骤进行[安装在](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) LAPTOPS上[启动OS X安装程序](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/)。
> > 确保安装盘已格式化为APFS格式并移除不必要的kext。
> 
> 大佬，我按照教程安装，但是出现了这个问题
> ![20190616213943](https://user-images.githubusercontent.com/33344292/59564946-7df58700-907f-11e9-984c-90b61450d044.jpg)

你好,我跟你出现了同样的问题,请问你的解决了么?
