### ISSUE TITLE
找不到Mac install 选项

### ISSUE THREAD

**Issue by aiisalive** [chuxubank/MSI-GP62-Hackintosh#3]
您好，我使用了您的这个clover来安装黑苹果，咱们的电脑型号和配置完全一样，但是我在启动的时候找不到mac install的选项，想问一下您这种问题应该怎么解决

**Comment by chuxubank** [comment]
安装方面的问题不在本项目讨论范围内，请参阅 #2 。
若之前能看到尝试删除 [这一行](https://github.com/chuxubank/MSI-GP62-Hackintosh/blob/a91f95527d538b3033bd19a8f10015a27eb0fd19/CLOVER/config.plist#L426) 试试。

**Comment by aiisalive** [comment]
![f1e6db7257e42a0f8e3c22c9e5dc7a4](https://user-images.githubusercontent.com/35070819/64304511-b346ac80-cfbe-11e9-8df1-b45eb567d31f.jpg)
大佬，我的显示的是这样的，只有win和Ubuntu两个启动项，没有mac安装选项，麻烦大佬帮我看一下这是怎么回事吧

**Comment by chuxubank** [comment]
请按照 [[Guide] Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) 中的步骤进行安装。
