### ISSUE TITLE
type-c 端口映射

### ISSUE THREAD

**Issue by CHN-STUDENT** [chuxubank/MSI-GP62-Hackintosh#9]
如题，我的是 GP-62-1281XCN(i5-6300HQ,GTX965m,16G,500g 960evo) 正在参考你的引导做 opencore 升级，我现在已经做了usb映射，但是type-c没法用，发现您也没有做端口映射，想咨询您关于这方面问题。此外我的屏幕亮度无法调节，休眠无法断电，唤醒黑屏，不知道您是否遇到这样的问题；我觉得还是 SSDT 问题，还想询问您折腾这方面的教程和资料？

**Comment by chuxubank** [comment]
我没有 Type-C 的设备所以确实没有用过，也没有做处理。
屏幕亮度应该就是 SSDT-PNLF 的问题了，WhateverGreen 里的，我应该也没有做什么修改直接用就可以了，注意快捷键默认是 F14 F15 也就是 F12 后的第二个键和第三个键。
休眠我也有问题，所以我现在都不休眠，平常不用的时候直接 hotcorner 关屏幕。
我所有的参考资料基本都在 README 里了。

**Comment by CHN-STUDENT** [comment]
我在windows下看 typec 占用 ss01-02 (3.0) 正反 / hs01-02 (2.0) 正反，我准备试试
此外我发现我的集显为 GFX0，独显 PEG0，和你的一样，但是不知道为何还是最低亮度且无法调节。
网上又找了一个其他版本的，亮度最亮了但是还是调节不了，还在研究。。

**Comment by CHN-STUDENT** [comment]
另外我看我们还有读卡器驱动也没有折腾：https://github.com/0xFireWolf/RealtekCardReaderFriend ，或许也可以试试

**Comment by chuxubank** [comment]
嗯嗯，加油！不过这个想折腾完美感觉是没有止境的，我目前是能满足日常使用就可以了，读卡器我目前也是用不到，不过感谢提醒和 repo 链接。

**Comment by CHN-STUDENT** [comment]
换了另外一个大佬的 SSDT-PNLF 屏幕亮度没问题了：https://github.com/ForceGT/Hackintosh--MSIGL62M-7RDX 。

但是后期我还有许多方向

- 寻找解决喇叭破音方案
- USB-TypeC 无法使用
- 休眠后启动无法使用。
- 后期折腾读卡器和完美触控板

以后还得跟你们好好学习多多完善。
谢谢您！

**Comment by CHN-STUDENT** [comment]
今天又试了下，typec端口就是 hs01/hs02和ss01/ss02，不要 `ssdt-uiac.aml` 和 `usbinjectall` ，只放一个 `usbports.kext` 加载就行了。
下一步研究其他的方向。
老哥也可以试试修下自己的 typeC 哈哈。
[归档.zip](https://github.com/chuxubank/MSI-GP62-Hackintosh/files/7381058/default.zip)

**Comment by CHN-STUDENT** [comment]
另外抓了一下日志，发现是 voodoops2 驱动问题造成无法休眠/睡眠，参照 [0ranko0P](https://github.com/0ranko0P/GL62M-7RD-Hackintosh/tree/OC_Bigsur_DW1820A/kexts#function-keys)大佬教程改了下，现在也成功了，感谢您们！

**Comment by CHN-STUDENT** [comment]
[VoodooPS2Controller.kext.zip](https://github.com/chuxubank/MSI-GP62-Hackintosh/files/7382384/VoodooPS2Controller.kext.zip)

**Comment by chuxubank** [comment]
@CHN-STUDENT 感谢分享！
> 另外抓了一下日志，发现是 voodoops2 驱动问题造成无法休眠/睡眠，参照 0ranko0P大佬教程改了下，现在也成功了，感谢您们！

请问这个日志是在什么位置？是类似于这种吗
```
2021-10-21 08:19:17.583459+0800  localhost kernel[0]: (VoodooPS2Mouse) <compose failure [UUID]>
```
以及我看 0ranko0P 和你发的 kext 貌似用的是 RehabMan 18年左右的驱动，是仅修改 Info.plist 就可以修复睡眠了吗？
我之前使用 Clover 的时候睡眠也是可以的，貌似用的也是这个驱动（也添加了相关的 Fn Key 的修复），我有时间试试，USB-C等我有设备了也试试。

**Comment by CHN-STUDENT** [comment]
@chuxubank 休眠失败强制重启不是会提示系统异常关机么，点击报告就能看到这些错误了，我之前也是用的最新版acidanthera 写的新版 [voodoops2] (https://github.com/acidanthera/voodoops2) ,  但是休眠异常，无法唤醒，且会造成所有输入设备失效，然后我就看了下日志，果然是 voodoops2 问题，我就寻思换一个老版本试试，结果看到 0ranko0P 的说明，用老版本就行了，还支持键盘映射。


此外昨天试了那个读卡器驱动，也有问题，所以不建议用了 hhh 。

**Comment by CHN-STUDENT** [comment]
错误日志：https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX/issues/21#issuecomment-947690278
此外隐藏 bios 里要设置 （右ctrl+右shit+左alt+f2一起按）
ACPI Settings
   └─ Enable Hibernation

参考这里：https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX#older_man-bios-configuration

**Comment by chuxubank** [comment]
好的！十分感谢，那个日志我一直没有研究过hhh

是的，老版本的 VoodooPS2 支持映射，而且可以直接用 hotpatch 修改（就不用编辑 Info.plist）了，我之前也发现过这个和睡眠有关hhh
